export const getData = () => [
  { imgSrc: "./assets/img/data/1/aladin.jpg", name: "aladin" },
  { imgSrc: "./assets/img/data/1/alice.png", name: "alice" },
  { imgSrc: "./assets/img/data/1/buzz.jpg", name: "buzz" },
  { imgSrc: "./assets/img/data/1/unicorn.png", name: "unicorn" },
  { imgSrc: "./assets/img/data/1/mowgli.jpg", name: "mowgli" },
  { imgSrc: "./assets/img/data/1/pinocchio.jpg", name: "pinocchio" },
  { imgSrc: "./assets/img/data/1/raiponce.jpg", name: "raiponce" },
  { imgSrc: "./assets/img/data/1/simba.jpg", name: "simba" },
  { imgSrc: "./assets/img/data/1/tarzan.jpg", name: "tarzan" },
  { imgSrc: "./assets/img/data/1/unicorn1.jpg", name: "unicorn1" },
  { imgSrc: "./assets/img/data/1/aladin.jpg", name: "aladin" },
  { imgSrc: "./assets/img/data/1/alice.png", name: "alice" },
  { imgSrc: "./assets/img/data/1/buzz.jpg", name: "buzz" },
  { imgSrc: "./assets/img/data/1/unicorn.png", name: "unicorn" },
  { imgSrc: "./assets/img/data/1/mowgli.jpg", name: "mowgli" },
  { imgSrc: "./assets/img/data/1/pinocchio.jpg", name: "pinocchio" },
  { imgSrc: "./assets/img/data/1/raiponce.jpg", name: "raiponce" },
  { imgSrc: "./assets/img/data/1/simba.jpg", name: "simba" },
  { imgSrc: "./assets/img/data/1/tarzan.jpg", name: "tarzan" },
  { imgSrc: "./assets/img/data/1/unicorn1.jpg", name: "unicorn1" },
];
